{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "hellocanary.serviceAccountName" . }}
  labels:
{{ include "hellocanary.labels" . | indent 4 }}
{{- end -}}
