apiVersion: v1
kind: Service
metadata:
  name: {{ include "hellocanary.fullname" . }}
  labels:
{{ include "hellocanary.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "hellocanary.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hellocanary.fullname" . }}-canary
  labels:
{{ include "hellocanary.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "hellocanary.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
