kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: success-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    interval: 30s
    initialDelay: 30s
    failureLimit: 5
    successCondition: result[0] >= 0.50
    failureCondition: result[0] < 0.50
    provider:
      prometheus:
        address: http://prometheus-operator-prometheus.monitoring.svc.cluster.local:9090
        query: |
          sum(rate(nginx_ingress_controller_requests{exported_service="{{args.service-name}}",status!~"[4-5].*"}[1m])) by (exported_service) / sum(rate(nginx_ingress_controller_requests{exported_service="{{args.service-name}}"}[1m])) by (exported_service)
