
replicaCount: 1

image:
  repository: docker.io/hatsunemiku/hellocanary
  tag: slow

envs:
  - name: TEST
    value: "3939"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  hosts:
    - host: 94c8817d.ngrok.io
      paths: ["/api/v2/*"]
